### ISSUE TITLE
Seeding

### ISSUE THREAD

**Issue by davrocks** [MinorMole/RcloneLab#1]
What are the steps to enable seeding/enabling port forwarding to the cloud instance? If I knew a certain IP address in my peers and their port number, could I add them? Google Colab seems to be able to support port forwarding to a local runtime, but I am not sure how to get seeding to work for BitTorrent. Thanks for the help!

**Comment by MinorMole** [comment]
There is no port forwarding for the Google Colab; the only thing that works is a reverse proxy. I never try BitTorrent on Linux before. Unfortunately, in WebUI of qBittorrent and rTorrent on the Linux, you can't add seed/peer. The only hope is the tracker can match seed and peer together.

If you have a client on the Linux with WebUI that can manually add seed/peer let me know, I'll try it.

**Comment by davrocks** [comment]
Do you know where I could find a guide to setup a reverse proxy(free or free trial) for Google Colab?

**Comment by MinorMole** [comment]
It already in [here](https://colab.research.google.com/github/MinorMole/RcloneLab/blob/master/RcloneLab.ipynb).

**Comment by davrocks** [comment]
Sorry, could you explain a little further about how to setup the reverse proxy? I tried out the notebook before I submitted the issue and couldn't find a way (I tried connecting to a free proxy in the connections tab of qbittorrent, but my torrents wouldn't seed).

**Comment by MinorMole** [comment]
@davrocks Here your guide and please read the warning.

> **Warning: you shouldn't use a reverse proxy for heavy data transferring; if so your reverse proxy will vanish or block completely.**

## Preparation

1. Install autossh.

```
!apt install autossh -qq -y
```

2. Insert my function.

``` python
def AutoSSH(name,port):
  get_ipython().system_raw("autossh -l " + name + " -M 0 -fNT -o 'StrictHostKeyChecking=no' -o 'ServerAliveInterval 300' -o 'ServerAliveCountMax 30' -R 80:localhost:" + port + " ssh.localhost.run &")
  get_ipython().system_raw("autossh -M 0 -fNT -o 'StrictHostKeyChecking=no' -o 'ServerAliveInterval 300' -o 'ServerAliveCountMax 30' -R " + name + ":80:localhost:" + port + " serveo.net &")
```

## How to use

For example, your WebUI using **8888** port and you want the link name **testproxy123**.

``` python
AutoSSH("testproxy123","8888")
```

Then your reverse proxy links will be...

`https://testproxy123.serveo.net`
`https://testproxy123.localhost.run`

> Note: use a unique name for the reverse proxy link, if someone already has taken your name the reverse proxy link will not work.

**Comment by davrocks** [comment]
What do I do with these proxy links? Putting them into the connections tab of the qbitorrent ui as a proxy didn't work; I am a bit confused.

**Comment by MinorMole** [comment]
If it didn't work, that means the proxy didn't support the µTP protocol.

**Comment by davrocks** [comment]
What should I do to correctly setup the reverse proxy then? 
I ran this code in google colab (replacing testproxy123 with a unique proxy name)
```
!apt install autossh -qq -y
def AutoSSH(name,port):
  get_ipython().system_raw("autossh -l " + name + " -M 0 -fNT -o 'StrictHostKeyChecking=no' -o 'ServerAliveInterval 300' -o 'ServerAliveCountMax 30' -R 80:localhost:" + port + " ssh.localhost.run &")
  get_ipython().system_raw("autossh -M 0 -fNT -o 'StrictHostKeyChecking=no' -o 'ServerAliveInterval 300' -o 'ServerAliveCountMax 30' -R " + name + ":80:localhost:" + port + " serveo.net &")
AutoSSH("testproxy123","8888")
```
Then I put in my connections tab and it looks like this:
![uiscreen](https://user-images.githubusercontent.com/22086968/60399708-bd12e600-9b1d-11e9-9c69-a607b64f92a2.PNG)
Thanks!
