### ISSUE TITLE
setup time zone freeze

### ISSUE THREAD

**Issue by K-E-N-W-A-Y** [MinorMole/RcloneLab#12]
setup time zone option not working correctly after the latest update

![image](https://user-images.githubusercontent.com/25846872/62335623-1a69d080-b4ea-11e9-86c1-a58cf15a6eb4.png)

**Comment by MinorMole** [comment]
Fix at https://github.com/MinorMole/RcloneLab/commit/c2b98bc5928742b0b461efddaff4a651e95f4040

**Comment by MinorMole** [comment]
@all-contributors add K-E-N-W-A-Y for bug

**Comment by MinorMole** [comment]
@all-contributors add @K-E-N-W-A-Y for bug
