### ISSUE TITLE
[Request] Option to use rclone beta

### ISSUE THREAD

**Issue by Sparoney** [MinorMole/RcloneLab#14]
Hey,

I was just wondering if it was possible for us to choose to use normal rclone or the beta (`curl https://rclone.org/install.sh | sudo bash -s beta`)

The reason why I'm asking is because of this issue https://github.com/rclone/rclone/issues/3348 fixed in the beta: https://github.com/rclone/rclone/commit/5be968c0cacb0fa13b338ec2208d6c2f2f583540

If not, I will just manually add the `-s beta` command to the install script on my end.

Thanks!

**Comment by MinorMole** [comment]
Updated > https://github.com/MinorMole/RcloneLab/commit/dfd2cea48d3366ca736861521fca670d7da5c6ab

**Comment by MinorMole** [comment]
@all-contributors add Sparoney for contribution

**Comment by MinorMole** [comment]
@all-contributors add Sparoney for code
