### ISSUE TITLE
Add RAR5 support in JDownloader

### ISSUE THREAD

**Issue by r9isgod8** [MinorMole/RcloneLab#15]
.jar files in /root/.JDownloader/libs needs to be updated with files from this [link](https://board.jdownloader.org/showthread.php?t=71069). There is no need to remove the existing files as JDownloader will automatically detect the new version of RAR. New RAR version will help in extracting files downloaded from snahp. Thanks.

**Comment by MinorMole** [comment]
Why the official release never update this? 🤔

**Comment by r9isgod8** [comment]
> Why the official release never update this? 🤔

Yeah, weird.I found out today itself and the extraction is now working.

**Comment by Xazmah** [comment]
@r9isgod8 How did you fixed it ? I still get errors with multi-parts downloaded rar files :/

**Comment by r9isgod8** [comment]
> @r9isgod8 How did you fixed it ? I still get errors with multi-parts downloaded rar files :/

Download zip from this [link (mega.nz/#!fjIWVAgT!ZyrxAyU26IfxDdmpBemMAer4DpzW06oIEAYboPMom98) and then extract the zip and copy two files inside the /root/.JDownloader/libs folder in your colab runtime. Restart JDownloader and enable archive extractor plugin.

**Comment by Xazmah** [comment]
@MinorMole Seems to be working fine now thanks for the update :)

**Comment by MinorMole** [comment]
> @MinorMole Seems to be working fine now thanks for the update :)
> BTW extracting 100Gb took about 10Min is it normal or slow ? Is it related to the libs or Jd ? Anyway to speeding up the process since colab has about 20Gb of ram and in the time of extraction it only use 2Gb to 3 ?

The speed limit is due to 2 cores CPU and lower than average clock speed. In order to increase speed, you need CPU, not RAM.

**Comment by r9isgod8** [comment]
How did you increased the RAM? I don't think Colab supports this natively.

**Comment by MinorMole** [comment]
> How did you increased the RAM? I don't think Colab supports this natively.

They rolling out just last week, not every account have this option though. I just received it today in my personal Gmail but not yet on my work Gmail.

**Comment by r9isgod8** [comment]
Okey thanks I am gonna try it. Btw where is the option to increase the RAM? Or it just does it automatically.

**Comment by MinorMole** [comment]
> Okey thanks I am gonna try it. Btw where is the option to increase the RAM? Or it just does it automatically.

It locates at Runtime > **Change runtime type**

**Comment by MinorMole** [comment]
@all-contributors add @r9isgod8 for ideas

**Comment by MinorMole** [comment]
@all-contributors add @Xazmah for usertesting
