### ISSUE TITLE
Setting up Reverse Proxy

### ISSUE THREAD

**Issue by davrocks** [MinorMole/RcloneLab#2]
Sorry to create a new issue, but the old one was closed. What should I do to correctly set up the reverse proxy then if the uTP wasn't supported? 
I ran this code in google colab (replacing testproxy123 with a unique proxy name)
```
!apt install autossh -qq -y
def AutoSSH(name,port):
  get_ipython().system_raw("autossh -l " + name + " -M 0 -fNT -o 'StrictHostKeyChecking=no' -o 'ServerAliveInterval 300' -o 'ServerAliveCountMax 30' -R 80:localhost:" + port + " ssh.localhost.run &")
  get_ipython().system_raw("autossh -M 0 -fNT -o 'StrictHostKeyChecking=no' -o 'ServerAliveInterval 300' -o 'ServerAliveCountMax 30' -R " + name + ":80:localhost:" + port + " serveo.net &")
AutoSSH("testproxy123","8888")
```
Then I put in my connections tab and it looks like this:
![uiscreen](https://user-images.githubusercontent.com/22086968/60399708-bd12e600-9b1d-11e9-9c69-a607b64f92a2.PNG)
(I tried disabling utp, but that didnt work either)
Thanks!

_Originally posted by @davrocks in https://github.com/MinorMole/RcloneLab/issues/1#issuecomment-507051400_

**Comment by MinorMole** [comment]
- Disable proxy server in the qBittorrent option (it, not the same as a reverse proxy and have nothing to do with it)
- Change auto ssh port to match the qBittorrent's port (in the picture is 13795)

If this still didn't work then I don't think it will work, good luck.

**Comment by davrocks** [comment]
Thanks for the tips. Unfortunately, the steps did not work.
