### ISSUE TITLE
move downloaded torrent

### ISSUE THREAD

**Issue by muhammedfurkan** [MinorMole/RcloneLab#28]
how can I move downloaded torrent file my google drive

**Comment by ShixAJ** [comment]
Run the First RcloneLab cell to upload your rclone.conf
Then in the second cell Select the "qBittorrent" Mode, Leave the Source field empty, in the Destination put the remote of your gdrive "remotename:path/to/folder" then run the cell.

Or Mount Gdrive, then in the utility there is cloud commander, run it and then open one links given to you as output, it will open a file explorer for you in a new tab. Use it to move the stuff you downloaded to your Gdrive.

The first method is the recommended way to move your stuff to your gdrive.
