### ISSUE TITLE
How can we download a torrent that is bigger than colab storage

### ISSUE THREAD

**Issue by ShixAJ** [MinorMole/RcloneLab#3]
The Title says it all. Can we make it upload finished files while downloading or something.

**Comment by MinorMole** [comment]
The only way I can think of is you have to select a certain number of file size that can fit in Colab storage. Then after first run complete, you upload them first then do this again for the rest of the file in the same torrent.

The bad news is qBittorrent WebUI and other clients that I have tried, have the same problem that you need to deselect file one by one manually. If your torrent has a ton of files, this is an impractical solution.

Maybe you should request a feature to [them](https://sourceforge.net/projects/qbittorrent/)?

**Comment by ShixAJ** [comment]
Ahh, Yeah thought so.
Could Jdownloader2 be added? (I know it is not related but I don't know where I can talk to you)

**Comment by MinorMole** [comment]
I too busy to try it. Will you help me test the Jdownloader2 command for a headless machine to run WebUI?

**Comment by ShixAJ** [comment]
I can try

**Comment by ShixAJ** [comment]
How can I contact you, Discord / Telegram /...

**Comment by MinorMole** [comment]
@ShixAJ Give me your Discord ID.

**Comment by ShixAJ** [comment]
Shix#5975
