### ISSUE TITLE
question

### ISSUE THREAD

**Issue by aaahimel** [MinorMole/RcloneLab#4]
![image](https://user-images.githubusercontent.com/43927831/61613222-88a8ca80-ac82-11e9-9332-0f7e19cdf99d.png)
How to get rclone.conf?

**Comment by MinorMole** [comment]
I have to ask you something first, do you have experience with rclone or Rclone Browser before?

**Comment by aaahimel** [comment]
nope .I don't.

**Comment by aaahimel** [comment]
Anyways. I have got the solution
