### ISSUE TITLE
Could you add a desktop?

### ISSUE THREAD

**Issue by Abu3safeer** [MinorMole/RcloneLab#7]
Hello, 
I found this gist but it don't work (installation field due to missing files), can you make it into RcloneLab? or create a fixed version?

https://gist.github.com/ahmedengu/9c04165fc303aebc8a5a2360234b28bf

**Comment by MinorMole** [comment]
My friend made a working version of this, but at this moment I don't have time to implement it for the end-user.

**Comment by K-E-N-W-A-Y** [comment]
@MinorMole can u post gist for that so we can test it before implement it with rclone lab.

thanks in advanced :)

**Comment by Abu3safeer** [comment]
@MinorMole  could you please tell me where? If you cannot implement this then no worries, I don't mind if it is part of RcloneLab or not, I just want a working version if possible.
